### ISSUE TITLE
Terminal process terminated with exit code 1

### ISSUE THREAD

**Issue by AlexMerz379** [Yidadaa/CMake-Test-Tools-VSCode#1]
Hello Yidadaa

First things first. Your extension is exactly what i was searching for a long time.
It is build up very practicaly and speeds up testing on big projects.

Unfortunately, i have some difficulty with the execution of the individual tests.
I am able to run all my tests and even if i register the individual test, it is fully running.
Your extension is parsing correctly all test in my cpp file and it is also building it correctly, but the execution command is failing all the time for individual tests.
**Overview Tests**
![image](https://github.com/Yidadaa/CMake-Test-Tools-VSCode/assets/71424781/de2c3f68-3bd6-40e7-85c8-fc236ef305e8)
**Failing command**
![image](https://github.com/Yidadaa/CMake-Test-Tools-VSCode/assets/71424781/698e9fcc-74e0-4f99-ba49-546a7c1c2bcb)

**What i tried**
-I tried do setting up the settings.json and launch.json, but wasn't able to get it running.
-The build target and target launch is the same as you documented it

Could you please give me some ideas how to fix it?

**Comment by Yidadaa** [comment]
Can you directly run the binary file shown in the image? Copy the full path of GeneratedTest.exe and run it directly in the command line, then check if it will throw an error.

**Comment by AlexMerz379** [comment]
Hello Yidadaa

Thank for the quick response. I run the command in the terminal and found out, that the libgcc_s_seh-1.dll was missing.
With adding of the two following lines in the CMakeLists.txt it solved the problem.

set(CMAKE_CXX_STANDARD_LIBRARIES "-static-libgcc -static-libstdc++ -lwsock32 -lws2_32 ${CMAKE_CSS_STANDARD_LIBRARIES}")
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive")

Now everything is working as it should.
Thank you Yidadaa for your help.

**Comment by Yidadaa** [comment]
Glad to hear that 😄
